### ISSUE TITLE
Cannot run the app

### ISSUE THREAD

**Issue by palcu** [crockpotveggies/tinderbox#1]
After I paste the token and click `Authorize` I get:

```
[debug] application - [mapdb] Database committer has persisted data to disk.
null
java.lang.UnsupportedClassVersionError: com/codahale/jerkson/JsonSnakeCase
	at com.codahale.jerkson.deser.CaseClassDeserializer.<init>(CaseClassDeserializer.scala:16)
	at com.codahale.jerkson.deser.ScalaDeserializers.findBeanDeserializer(ScalaDeserializers.scala:92)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory._findCustomBeanDeserializer(BeanDeserializerFactory.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:130)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:399)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:348)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:261)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:241)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:394)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3169)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3028)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1681)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:93)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:108)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Uncaught error from thread [play-akka.actor.default-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
java.lang.UnsupportedClassVersionError: com/codahale/jerkson/JsonSnakeCase
	at com.codahale.jerkson.deser.CaseClassDeserializer.<init>(CaseClassDeserializer.scala:16)
	at com.codahale.jerkson.deser.ScalaDeserializers.findBeanDeserializer(ScalaDeserializers.scala:92)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory._findCustomBeanDeserializer(BeanDeserializerFactory.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:130)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:399)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:348)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:261)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:241)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:394)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3169)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3033)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1681)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:93)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:115)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
[ERROR] [02/10/2015 11:24:57.501] [play-akka.actor.default-dispatcher-7] [ActorSystem(play)] Uncaught error from thread [play-akka.actor.default-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.UnsupportedClassVersionError: com/codahale/jerkson/JsonSnakeCase
	at com.codahale.jerkson.deser.CaseClassDeserializer.<init>(CaseClassDeserializer.scala:16)
	at com.codahale.jerkson.deser.ScalaDeserializers.findBeanDeserializer(ScalaDeserializers.scala:92)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory._findCustomBeanDeserializer(BeanDeserializerFactory.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:130)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:399)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:348)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:261)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:241)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:394)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3169)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3033)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1681)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:93)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15)
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:115)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)

	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] a.a.ActorSystemImpl - Uncaught error from thread [play-akka.actor.default-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.UnsupportedClassVersionError: com/codahale/jerkson/JsonSnakeCase
	at com.codahale.jerkson.deser.CaseClassDeserializer.<init>(CaseClassDeserializer.scala:16) ~[jerkson_2.10-0.6.3.jar:0.6.3]
	at com.codahale.jerkson.deser.ScalaDeserializers.findBeanDeserializer(ScalaDeserializers.scala:92) ~[jerkson_2.10-0.6.3.jar:0.6.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory._findCustomBeanDeserializer(BeanDeserializerFactory.java:104) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:130) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:399) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:348) ~[jackson-databind-2.4.4.jar:2.4.4]
```

**Comment by crockpotveggies** [comment]
@palcu looks like a conflicting Java version. Can you try downloading the latest Java JDK? It looks like it is trying to run it with Java 6.

**Comment by albertolive** [comment]
Me too and I have downloaded last Java JDK update

**Comment by albertolive** [comment]
I fixed downloading this version: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html?ssSourceSiteId=otnes

**Comment by iamrekcah** [comment]
I can confirm! I had the same issue, and it was resolved by installing `java-1.8.0-openjdk`.

**Comment by PetrShypila** [comment]
Had the same issue with Apple Java 6. Works well with Oracle JDK 7u45

**Comment by crockpotveggies** [comment]
I've added a note to the wiki about these type of issues. I will also link to this particular issue so that if anyone has further suggestions or problems they can paste them here.

**Comment by wnstnsmth** [comment]
The process of editing code and building the app again after the recent changes is not entirely clear to me. Some days ago, I used
```
sbt clean
sbt compile
sbt run
```
to build and run the app after I had changed FunMessages.scala.
Now I pulled the latest commits and wanted to build again, because I still have a modified FunMessages.scala. What do I have to do now? Will repeating the same three steps be enough to build and run the new app? I don't really understand what's written in https://github.com/crockpotveggies/tinderbox/wiki/Editing-the-Code - `sbt compile` is not mentioned anymore.

**Comment by crockpotveggies** [comment]
I made a couple modifications to that wiki page so it was clear which section is dedicated to building. All you need to is run `bash lib/build_tinderbox_dist` from the project root directory, and that script will take care of everything else.

**Comment by mshaban** [comment]
@crockpotveggies 

I get this message when clicking on Authorise
 any ideas why ?
```
com.fasterxml.jackson.databind.JsonMappingException: Invalid JSON. Needed [token, globals, user, versions], but found [code, error].
java.lang.Exception: Data was not wrapped in a results class. Could not parse.
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:109)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[error] play - Cannot invoke the action, eventually got an error: com.codahale.jerkson.ParsingException: Invalid JSON. Needed [status, error], but found [code, error].
[error] application - 

! @6mmmp3efd - Internal server error, for (POST) [/authenticate] ->

play.api.Application$$anon$1: Execution exception[[ParsingException: Invalid JSON. Needed [status, error], but found [code, error].]]
	at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
Caused by: com.codahale.jerkson.ParsingException: Invalid JSON. Needed [status, error], but found [code, error].
	at com.codahale.jerkson.ParsingException$.apply(ParsingException.scala:9) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:88) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:115) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid JSON. Needed [status, error], but found [code, error].
	at com.codahale.jerkson.deser.CaseClassDeserializer.deserialize(CaseClassDeserializer.scala:71) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3038) ~[com.fasterxml.jackson.core.jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1681) ~[com.fasterxml.jackson.core.jackson-databind-2.4.4.jar:2.4.4]
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:93) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
	at utils.tinder.TinderApi$$anon$1.parse(TinderApi.scala:22) ~[default.tinderbox-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
	at com.codahale.jerkson.Parser$class.parse(Parser.scala:15) ~[com.cloudphysics.jerkson_2.10-0.6.3.jar:0.6.3]
```
