### ISSUE TITLE
Memory leaks / hogging

### ISSUE THREAD

**Issue by charukiewicz** [crockpotveggies/tinderbox#25]
Running this application on an older machine with 4 GB of RAM.  With Chrome and some other stuff open I am at around 45% usage.  Then, within 30 seconds of `sbt run` I am up to 99% memory usage and the machine begins freezing.

Is there a specific reason as to why tinderbox uses so much RAM?  Can it be optimized / limited?

**Comment by crockpotveggies** [comment]
Unfortunately SBT and Java in general are memory hogs. I developed Tinderbox on 8GB so I was unaware of the effects on older machines.

At first thought, the best way I can think of to optimize it is compiling the app into a distributable JAR. That way the settings required to run it would be much smaller than standard machines. I might merge this with another issue that's focused on similar problems (https://github.com/crockpotveggies/tinderbox/issues/7). The solution would be the same in both cases

**Comment by monksy** [comment]
> Unfortunately SBT and Java in general are memory hogs. 

That usually means that you have a memory leak and you are holding on to more information than what you need to.

**Comment by crockpotveggies** [comment]
Agreed, and I've looked at using different garbage collectors to help the problem. One of my ways to fix these errors is to create a dist package and run the app without SBT.

**Comment by crockpotveggies** [comment]
Added a new commit to eliminate SBT. Hopefully this simplifies how things are running in the JVM and problems with classes not being loaded into the classpath. Going to close this issue (and a few others related to it). Please comment here if memory leak issues continue to occur.

**Comment by charukiewicz** [comment]
Thanks for fixing this.  I just pulled and tried to run this but noticed that there's no `/dist/tinderbox-1.1-SNAPSHOT/bin/tinderbox` file to run.  In fact that `/bin` directory doesn't exist at all.  Is there some other pre-run step?

**Comment by crockpotveggies** [comment]
Sorry, I didn't realize there was a catch-all in the `.gitignore` file that was affecting this. I'm putting up a fix shortly!

**Comment by crockpotveggies** [comment]
Fixed.

**Comment by charukiewicz** [comment]
Great!  Pulled and left this on overnight last night.

Results:  Tinderbox was the only open application (closed Chrome, etc.).  Initially it did use substantially less RAM than before (400-500 MB total).  When I checked it this morning, the terminal log showed that the application had still crashed due to the same error reported in #7.

Looks like the dist package helps with decreasing initial RAM usage but there's still some garbage cleanup that is not happening somewhere in the application.

I wanted to also say thanks for improving this application.  This is really a cool project.

**Comment by crockpotveggies** [comment]
Glad to improve it, I want to leave it in a somewhat decent state before I move on from the project so others have something to build from.

Re: mem leak. Something must be happening internally. Either the Akka actors aren't being cleaned up properly, which may indicate `PoisonPill` is failing. There's also a possibility that the leak is caused by MapDB, since I know the version used with this project is still a little young. Not sure yet, it will take some IntelliJ profiling and debugging, maybe JMX metrics, to find the root cause.
